/**************************************************************************
 * C S 429 system emulator
 * 
 * instr_Decode.c - Decode stage of instruction processing pipeline.
 **************************************************************************/ 

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <assert.h>
#include "err_handler.h"
#include "instr.h"
#include "instr_pipeline.h"
#include "forward.h"
#include "machine.h"
#include "hw_elts.h"

#define SP_NUM 31
#define XZR_NUM 32

extern machine_t guest;
extern mem_status_t dmem_status;

extern int64_t W_wval;

/*
 * Control signals for D, X, M, and W stages.
 * Generated by D stage logic.
 * D control signals are consumed locally. 
 * Others must be buffered in pipeline registers.
 * STUDENT TO-DO:
 * Generate the correct control signals for this instruction's
 * future stages and write them to the corresponding struct.
 */

static comb_logic_t 
generate_DXMW_control(opcode_t op,
                      d_ctl_sigs_t *D_sigs, x_ctl_sigs_t *X_sigs, m_ctl_sigs_t *M_sigs, w_ctl_sigs_t *W_sigs) {

    D_sigs->src2_sel = 0;
    if (op == OP_STUR) {
        D_sigs->src2_sel = 1;
    }

    switch (op) {
        case OP_ADDS_RR:
        case OP_SUBS_RR:
        case OP_CMP_RR:
        case OP_MVN:
        case OP_ORR_RR:
        case OP_EOR_RR:
        case OP_ANDS_RR:
        case OP_TST_RR:
        case OP_CSEL:
        case OP_CSINV:
        case OP_CSINC:
        case OP_CSNEG:
            X_sigs->valb_sel = 1;
            break;
        default:
            X_sigs->valb_sel = 0;
            break;
    }

    switch (op) {
        case OP_ADDS_RR:
        case OP_SUBS_RR:
        case OP_CMP_RR:
        case OP_ANDS_RR:
        case OP_TST_RR:
            X_sigs->set_CC = 1;
            break;
        default:
            X_sigs->set_CC = 0;
            break;
    }

    M_sigs->dmem_read = 0;
    if (op == OP_LDUR) {
        M_sigs->dmem_read = 1;
    }

    M_sigs->dmem_write = 0;
    if (op == OP_STUR) {
        M_sigs->dmem_write = 1;
    }

    W_sigs->dst_sel = 0;
    if (op == OP_BL || op == OP_BLR) {
        W_sigs->dst_sel = 1;
    }

    W_sigs->wval_sel = 0;
    if (op == OP_LDUR) {
        W_sigs->wval_sel = 1;
    }

    W_sigs->w_enable = 1;
    switch (op) {
        case OP_STUR:
        case OP_B:
        case OP_B_COND:
        case OP_RET:
        case OP_NOP:
        case OP_HLT:
        case OP_CMP_RR:
        case OP_TST_RR:
        case OP_CBNZ:
        case OP_CBZ:
            W_sigs->w_enable = 0;
            break;
        default:
            break;
    }

    return;
}

/*
 * Logic for extracting the immediate value for M-, I-, and RI-format instructions.
 * STUDENT TO-DO:
 * Extract the immediate value and write it to *imm.
 */

static comb_logic_t 
extract_immval(uint32_t insnbits, opcode_t op, int64_t *imm) {

    switch (op) {
        case OP_LDUR:
        case OP_STUR:
            *imm = bitfield_s64(insnbits, 12, 9);
            break;
        case OP_MOVK:
        case OP_MOVZ:
            *imm = bitfield_u32(insnbits, 5, 16);
            break;
        case OP_ADRP:;
            uint32_t high = bitfield_u32(insnbits, 5, 18);
            uint32_t low = bitfield_u32(insnbits, 29, 2);
            *imm = (high << 14) | (low << 12);
            break;
        case OP_LSL:
            *imm = 64 - bitfield_u32(insnbits, 16, 6);
            break;
        case OP_LSR:
            *imm = bitfield_u32(insnbits, 16, 6);
            break;
        case OP_ADD_RI:
        case OP_SUB_RI:
        case OP_UBFM:
        case OP_ASR:
            *imm = bitfield_u32(insnbits, 10, 12);
            break;
        default:
            *imm = 0;
            break;
    }
    return;
}

/*
 * Logic for determining the ALU operation needed for this opcode.
 * STUDENT TO-DO:
 * Determine the ALU operation based on the given opcode
 * and write it to *ALU_op.
 */
static comb_logic_t
decide_alu_op(opcode_t op, alu_op_t *ALU_op) {

    switch (op) {
        case OP_STUR:
        case OP_LDUR:
        case OP_ADRP:
        case OP_ADD_RI:
        case OP_ADDS_RR:
            *ALU_op = PLUS_OP;
            break;
        case OP_SUB_RI:
        case OP_SUBS_RR:
        case OP_CMP_RR:
            *ALU_op = MINUS_OP;
            break;
        case OP_MVN:
            *ALU_op = INV_OP;
            break;
        case OP_ORR_RR:
            *ALU_op = OR_OP;
            break;
        case OP_EOR_RR:
            *ALU_op = EOR_OP;
            break;
        case OP_ANDS_RR:
        case OP_TST_RR:
            *ALU_op = AND_OP;
            break;
        case OP_MOVK:
        case OP_MOVZ:
            *ALU_op = MOV_OP;
            break;
        case OP_LSL:
            *ALU_op = LSL_OP;
            break;
        case OP_LSR:
            *ALU_op = LSR_OP;
            break;
        case OP_ASR:
            *ALU_op = ASR_OP;
            break;
        case OP_CBZ:
            *ALU_op = CBZ_OP;
            break;
        case OP_CBNZ:
            *ALU_op = CBNZ_OP;
            break;
        case OP_CSEL:
            *ALU_op = CSEL_OP;
            break;
        case OP_CSINV:
            *ALU_op = CSINV_OP;
            break;
        case OP_CSINC:
            *ALU_op = CSINC_OP;
            break;
        case OP_CSNEG:
            *ALU_op = CSNEG_OP;
            break;
        default:
            *ALU_op = PASS_A_OP;
            break;
    }
    return;
}

/*
 * Utility functions for copying over control signals across a stage.
 * STUDENT TO-DO:
 * Copy the input signals from the input side of the pipeline
 * register to the output side of the register.
 */

comb_logic_t 
copy_m_ctl_sigs(m_ctl_sigs_t *dest, m_ctl_sigs_t *src) {
    dest->dmem_read = src->dmem_read;
    dest->dmem_write = src->dmem_write;
    return;
}

comb_logic_t 
copy_w_ctl_sigs(w_ctl_sigs_t *dest, w_ctl_sigs_t *src) {
    dest->dst_sel = src->dst_sel;
    dest->w_enable = src->w_enable;
    dest->wval_sel = src->wval_sel;
    return;
}

comb_logic_t
extract_regs(uint32_t insnbits, opcode_t op, 
             uint8_t *src1, uint8_t *src2, uint8_t *dst) {

    switch (op) {
        case OP_MOVK:
        case OP_MOVZ:
        case OP_B:
        case OP_B_COND:
        case OP_BL:
        case OP_NOP:
        case OP_HLT:
            break;
        case OP_CBZ:
        case OP_CBNZ:
            *src1 = bitfield_u32(insnbits, 0, 5);
            break;
        default:
            *src1 = bitfield_u32(insnbits, 5, 5);
            break;
    }
    
    if (*src1 == SP_NUM) {
        switch (op) {
            case OP_LDUR:
            case OP_STUR:
            case OP_ADD_RI:
            case OP_SUB_RI:
                break;
            default:
                *src1 = XZR_NUM;
        }
    }

    switch (op) {
        case OP_STUR:
            *src2 = bitfield_u32(insnbits, 0, 5);
            break;
        case OP_ADD_RI:
        case OP_ADDS_RR:
        case OP_SUB_RI:
        case OP_SUBS_RR:
        case OP_CMP_RR:
        case OP_MVN:
        case OP_ORR_RR:
        case OP_EOR_RR:
        case OP_ANDS_RR:
        case OP_TST_RR:
        case OP_CSEL:
        case OP_CSINV:
        case OP_CSINC:
        case OP_CSNEG:
            *src2 = bitfield_u32(insnbits, 16, 5);
            break;
        default:
            break;
    }

    if (*src2 == SP_NUM) {
        *src2 = XZR_NUM;
    }

    // determine destination
    switch (op) {
        case OP_BL:
        case OP_BLR:
            *dst = 30;
            break;
        case OP_B_COND:
        case OP_B:
        case OP_RET:
        case OP_NOP:
        case OP_HLT:
        case OP_CBZ:
        case OP_CBNZ:
        case OP_BR:
            break;
        default:
            *dst = bitfield_u32(insnbits, 0, 5);
            break;
    }

    if (op == OP_MOVK) {
        *src1 = *dst;
    }

    if (*dst == SP_NUM) {
        switch (op) {
            case OP_ADD_RI:
            case OP_SUB_RI:
                break;
            default:
                *dst = XZR_NUM;
        }
    }
    
    return;
}

/*
 * Decode stage logic.
 * STUDENT TO-DO:
 * Implement the decode stage.
 * 
 * Use `in` as the input pipeline register,
 * and update the `out` pipeline register as output.
 * Additionally, make sure the register file is updated
 * with W_out's output when you call it in this stage.
 * 
 * You will also need the following helper functions:
 * generate_DXMW_control, regfile, extract_immval,
 * and decide_alu_op.
 */

comb_logic_t decode_instr(d_instr_impl_t *in, x_instr_impl_t *out) {
    out->op = in->op;
    out->print_op = in->print_op;
    out->seq_succ_PC = in->seq_succ_PC;
    out->status = in->status;
    d_ctl_sigs_t D_sigs_t;
    generate_DXMW_control(in->op, &(D_sigs_t), &(out->X_sigs), &(out->M_sigs), &(out->W_sigs));
    decide_alu_op(in->op, &(out->ALU_op));

    uint8_t src1 = 31;
    uint8_t src2 = 31;
    extract_regs(in->insnbits, in->op, &src1, &src2, &(out->dst));
    bool enable = W_out->W_sigs.w_enable && W_out->status == STAT_AOK;
    regfile(src1, src2, W_out->dst, W_wval, enable, &(out->val_a), &(out->val_b));

    forward_reg(src1, src2, X_out->dst, M_out->dst, W_out->dst, M_in->val_ex, M_out->val_ex, W_in->val_mem, W_out->val_ex,
        W_out->val_mem, M_out->W_sigs.wval_sel, W_out->W_sigs.wval_sel, X_out->W_sigs.w_enable, M_out->W_sigs.w_enable, 
        W_out->W_sigs.w_enable, &(out->val_a), &(out->val_b));

    if (in->op == OP_B_COND) {
        out->cond = bitfield_u32(in->insnbits, 0, 4);
    }
    
    if (in->op == OP_CSEL || in->op == OP_CSINV || in->op == OP_CSNEG || in->op == OP_CSINC) {
        out->cond = bitfield_u32(in->insnbits, 12, 4);
    }

    if (in->op == OP_ADRP) {
        out->val_a = in->adrp_val;
    }

    out->val_imm = 0;
    extract_immval(in->insnbits, in->op, &(out->val_imm));
    out->val_hw = 0;

    if (in->op == OP_MOVZ) {
        out->val_hw = bitfield_u32(in->insnbits, 21, 2) << 4;
    }
    else if (in->op == OP_MOVK) {
        out->val_hw = bitfield_u32(in->insnbits, 21, 2) << 4;
        out->val_a = out->val_a & ~(0xFFFFUL << out->val_hw);
    }
    else if (in->op == OP_ADD_RI || in->op == OP_SUB_RI) {
        out->val_hw = bitfield_u32(in->insnbits, 22, 1);
    }

    return;
}
